# Generated by Django 3.0.4 on 2020-03-26 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('coordinates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('wind_speed', models.CharField(max_length=50)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather',
                'db_table': 'weather',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='WeatherJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fk_weather', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather.Weather')),
            ],
            options={
                'verbose_name': 'WeatherJournal',
                'db_table': 'weather_journal',
                'ordering': ('pk',),
            },
        ),
    ]
